language: node_js
node_js:
  - 12
cache:
  directories:
    - node_modules
script:
  - npm run eslint
  - npm run build
  - npm run export
  - touch out/.nojekyll
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: out
  fqdn: studyo.tk # This instructs Travis to create a CNAME file with wallisconsultancy.co.uk as the contents on every deployment to the gh-pages branch
  on:
    branch: master
